/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bomb.glb --transform --shadows 
Files: bomb.glb [5.84MB] > /Users/daniyal.farooque/Documents/JSProject/Mario-Kart-3.js/public/models/items/bomb-transformed.glb [192.02KB] (97%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bomb-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.LE_Bomb.geometry} material={materials.bomb} />
    </group>
  )
}

useGLTF.preload('/bomb-transformed.glb')
